name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check formatting
        uses: psf/black@stable
        with:
          options: '--check --diff --include \.sage$'
      - name: Format and commit changed files
        if: ${{ failure() }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          if git commit -m "Auto-formatted code using black"; then
            git push;
          fi
