name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Format files
        uses: psf/black@stable
        with:
          options: '--include \.(sage|pyi?)$'
      - name: Commit changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          if git commit -m "Auto-formatted code using black"; then
            git push;
          fi
